services:
  - type: web
    name: desafio24
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_TOKEN
        generateValue: true
      - key: DATABASE_URL
        sync: false
